language: csharp
mono: none

solution: ./core/BGC.sln

jobs:
  include:
    - name: Windows
      os: windows
      before_install:
        - choco install dotnetcore-sdk

    - name: Linux
      os: linux
      dotnet: 3.1.100

install:
  - dotnet tool restore
  - dotnet restore core

script:
  - dotnet build core
  - dotnet test core