language: csharp
mono: none

solution: ./core/BGC.sln

jobs:
  include:
    - name: Windows
      os: windows
      before_install:
        - choco install dotnetcore-sdk --version=2.2.102

    - name: Linux
      os: linux
      dotnet: 2.2.102

install:
  - dotnet tool restore
  - dotnet restore core

script:
  - dotnet build core
  - dotnet test core